# region depends on Worldguard
# group depends on vault
parameters:
  region:
    enabled: true
    aliases: [rg, region]
  group:
    enabled: true
    aliases: [gr, group]
actions:
  - player-balanceupdate