name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${plugin.mainClass}
softdepend: [WorldGuard, Vault, Essentials]
depend: [Prism]
commands:
  moreprism:
    permission: moreprism.reload
    usage: /<command> reload